### ISSUE TITLE
Closing window leaves user unable to reopen window without restarting app

### ISSUE THREAD

**Issue by tofagerl** [jellybeansoup/macos-netflix#1]
Great app! Have been looking for something like this for a while. Closest I got was one of those generic site-app makers, but I could never get always-on-top that way.

Anyway, when I closed the window I was unable to find a way to reopen a window from within the app. Quiting the app works, since a new window appears when I restart the app. 

Easy solution: Either close the app automatically once window closes, or make a shortcut (cmd-n or cmd-1 seem the most obvious candidates) to open a window from the app when it is closed.
Hell, you could also allow more than one window, but that probably has more than a few side-effects.

**Comment by pflats** [comment]
To add on: If no windows exist, clicking the dock icon should also create one.

That said, since this doesn't seem to be document-based (nor do I imagine you plan for it to be in the future) it seems appropriate terminate the app when the window is closed. 

If Netflix expands to podcast-like audio-only features, though, some users may expect the app to behave like iTunes. That seems unlikely enough to ignore and minor enough to handle with a "Closing the window will terminate playback. Sure you want to close? [ ] show this again?" dialog, but it came to mind when I hovered over the go button.

**Comment by jellybeansoup** [comment]
Opening multiple windows can be a bit of a bad idea with Netflix. If they detect too many open browser tabs/windows/etc, they'll stop playing stuff until you close some. That said, I can see an argument for allowing browsing and watching simultaneously, but I think I'd choose to err on the side of simplicity… for now, at least.

Thus, I agree. The most obvious answer is to simply terminate when closing the window. I'll get that added as soon as I can.

**Comment by jyounus** [comment]
I've also experienced a similar issue when I accidentally minimised the window. After clicking on the dock icon again, the window did animate to appear back on screen but then is instantly gone.

(In other words, pressing the yellow minimise button in the top left also causes issues and doesn't make the window reappear. I built the project from source).

**Comment by jellybeansoup** [comment]
@jyounus I've run a very quick and dirty test on the upcoming version, and it seems like i must have fixed that problem along with another (probably #5?).

If you notice it after updating to v1.0.1 (available very soon), feel free to create a new issue, and I'll jump on it.
