### ISSUE TITLE
Download still contains 1.0.3 instead of 1.0.4

### ISSUE THREAD

**Issue by suschizu** [jellybeansoup/macos-netflix#18]
Hello - I think you forgot to update the version number in 1.0.4

![image](https://user-images.githubusercontent.com/16004333/102356581-aa100200-3fad-11eb-802b-88595a8a1b9e.png)

**Comment by core-code** [comment]
i can confirm the issue

**Comment by jellybeansoup** [comment]
Thanks for the heads up! This is a mistake on my part; I simply forgot to update the version number within the Info.plist (as fixed by #19, which has been merged). I can confirm that the download is indeed v1.0.4, it's just incorrectly labelled.

I need to push an update to add proper Apple Silicon support anyway, so the next download will be v1.0.5, and I'll make sure to properly update the version number this time 😂

**Comment by core-code** [comment]
thanks!
