### ISSUE TITLE
Video not visible

### ISSUE THREAD

**Issue by mehulb** [jellybeansoup/macos-netflix#20]
Once you start playing a video either the video is not visible or an error message is seen (from Netflix). Refer attachment.
<img width="1392" alt="Screenshot 2021-01-23 at 3 14 56 PM" src="https://user-images.githubusercontent.com/22584657/105574940-d3326800-5d8d-11eb-846c-1cda35cef04f.png">

**Comment by jellybeansoup** [comment]
There's nothing I can do about this. All the app does is provide a standalone web view, and otherwise Netflix will be presented the same way it would be in a Safari tab.

Best I can offer is: Ensure that you're able to play videos from Netflix within Safari (on that monitor, if it's an external one). Try closing the app and opening again. If you are using an external monitor, try disconnecting and reconnecting it, making sure the connection is clean.
