### ISSUE TITLE
PiP support

### ISSUE THREAD

**Issue by BenRiceM** [jellybeansoup/macos-netflix#6]
Because it works really nicely with multiple Spaces and full-screen apps.

**Comment by MaxHasADHD** [comment]
Would that be possible? I've tried some PiP extensions but they never work with Netflix. Unsure if Netflix wants it supported, for unknown reasons.

**Comment by jellybeansoup** [comment]
PiP is _technically_ possible, Netflix doesn’t really do anything to prevent it other than not provide a button (and disable right clicking in general).

@BenRiceM If I was able to get the app’s window to float between spaces, would that satisfy your PiP needs?

**Comment by ToniWonKanobi** [comment]
@MaxHasADHD I've tried two picture-in-picture Safari extensions/apps over the past few years. After using each extension for a while, Netflix eventually stopped working correctly sometime in the Fall of 2017.

See similar issues for [PiPifier](https://github.com/arnoappenzeller/PiPifier/issues/47) and [PiedPiPer](https://github.com/JoeKuhns/PiedPiPer.safariextension/issues/30).

**Comment by jellybeansoup** [comment]
@ToniWonKanobi I used PiedPiPer for a while, it's still installed on my system. Doesn't work for Netflix at all any more, and only occasionally for YouTube.

That said, I've taken to more direct _developer-y_ work arounds: for Netflix, disabling javascript, right clicking to switch to PiP, and then quickly re-enabling javascript will work. Similarly, right clicking a YouTube video, then right clicking again while the custom menu is open will allow you to switch to PiP.

There's always a way, but futzing too much with Netflix's UI is an infinite quest. They'll inevitably change something and whatever customisation you made (like injecting a PiP button) will stop working.

**Comment by ToniWonKanobi** [comment]
> That said, I've taken to more direct developer-y work arounds: for Netflix, disabling javascript, right clicking to switch to PiP, and then quickly re-enabling javascript will work.

@jellybeansoup Toggling JavaScript!? What has this world come to 😆 I do the YouTube switch thing and that works reasonably well.

> There's always a way, but futzing too much with Netflix's UI is an infinite quest. They'll inevitably change something and whatever customisation you made (like injecting a PiP button) will stop working.

Tell me about it. I have a custom stylesheet in Safari, and between Netflix and YouTube, it's *so* difficult to try and target things with `class`'s and `id`'s because they're dynamically generated and stuff 🙄

**Comment by jellybeansoup** [comment]
There's still some work to do on this before I'd consider it release-worthy, but I've started adding support for a proper PiP-style floating behaviour. This commit should allow it to float above fullscreen apps, and between spaces, but the behaviour is slightly jarring (it's not a smooth transition, just an immediate jump), and it introduces other problems (can't fullscreen).

I'll work on resolving these, and in the meantime, you can build directly from [the floating-behaviour branch](https://github.com/jellybeansoup/macos-netflix/tree/floating-behaviour) to get it right now (or to assist with its development).

**Comment by bkniffler** [comment]
I'm not a MacOS/swift dev, but why can't you use the native picture in picture functionality of MacOS as used in https://github.com/avaidyam/PIP-Demo/blob/master/piptest/ViewController.swift

**Comment by jellybeansoup** [comment]
@bkniffler Having only briefly looked at the link you posted: I probably could. I wasn't aware it was a thing (because I'm only barely a macOS dev at this point; my bread and butter is iOS).

I will look into it further and see if it's something I can use.

**Comment by MaxHasADHD** [comment]
Any update on this?

**Comment by jellybeansoup** [comment]
@MaxHasADHD Only that I haven't had the opportunity to look into implementing it, as I've been swamped with other work.

**Comment by jellybeansoup** [comment]
Many months later, and I've (finally) been able to investigate potentially using the private `PIPViewController` class (and the various other related classes that power its behaviour). Unfortunately, the overall issue is that this class is very specifically built to accomodate video, which Is somewhat redundant for this project's needs: if I wanted to pop the videos out of the interface, I could use javascript to do so in a similar way to how some Safari extensions handle it, and it's doesn't appear possible to actually render the app itself within such a window due to its presentation requirements.

Thanks again to @bkniffler for the suggestion 😊

I'm (slowly) continuing work on achieving the desired behaviour via a custom implementation; all the progress I make on this will be reflected in [the floating-behaviour branch](https://github.com/jellybeansoup/macos-netflix/tree/floating-behaviour).
